Debugging test report

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -36,6 +36,10 @@ jobs:
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
 
+      #Ensure reports folder exists
+      - name: Ensure report folder exists
+        run: mkdir -p reports/playwright-report
+
       # Run all Playwright tests
       - name: Run Playwright Tests
         run: |
@@ -51,7 +55,7 @@ jobs:
         with:
           name: playwright-report
           path: reports/playwright-report
-      - run: ls -la reports/playwright-report
+      - run: ls -la reports/playwright-report || echo "Folder not found"
 
       # # 8️⃣ Upload videos/screenshots of failed tests
       # - name: Upload Playwright Videos
